### ISSUE TITLE
GRIB2 request: clarify names For leaf area index

### ISSUE THREAD

**Issue by mo-marqh** [MetOffice/localTables-GRIB-BUFR#59]
*Please note that it is fine to group together a number of requests in a single GitHub issue.*

Please provide the following information (if applicable): 

- Reason for request  
    - for enhanced clarity of meaning
- Met Office Local Table (e.g. Surface Type, Parameter)  
    - parameter
- Definition name
    - add the phrase `leaf area index of` to all of the relevant 2-0- codes 
    - this is the coverage of leaves, as seen from above, how many leaves are between the observer and the ground, on average across 
- GRIB2 code (number between 192-254) 
  - already assigned
- Description 
- Units (if applicable)

**Comment by bjwheltor** [comment]
For the update for the Leaf Area Index vegetation types:

STASH code | Parameter  | Description | Unit | Discipline | Category | Number
-- | -- | -- | -- | -- | -- | --
3318 | primary deciduous trees |   | 1 | 2 | 0 | 192
3318 | primary evergreen trees |   | 1 | 2 | 0 | 193
3318 | natural grasses of C3 plant functional types |   | 1 | 2 | 0 | 194
3318 | natural grasses of C4 plant functional types |   | 1 | 2 | 0 | 195
3318 | shrubs |   | 1 | 2 | 0 |  196

I suggest the text:
1. Prefixing the "Parameter" text with "leaf area index of "
2. Adding "Description" text "Leaf Area Index is a measure for the total area of leaves per unit ground area and directly related to the amount of light that can be intercepted by plants." (the second part can be dropped if this is considered too long.
