### ISSUE TITLE
GRIB2 request: latent heat flux

### ISSUE THREAD

**Issue by feggleton** [MetOffice/localTables-GRIB-BUFR#61]
Require a local code for latent heat flux parameter as WMO code (0-0-10) is net flux and this parameter is positive upward (i.e., away from the surface). So in terms of the CF standard name, it would be: surface_upward_latent_heat_flux.

- Reason for request
SEA CAM model required - no existing code
- Met Office Local Table (e.g. Surface Type, Parameter)
parameter
- Definition name
latent heat flux
- GRIB2 code (number between 192-254)
0-0-193

- Description

- Units (if applicable)

**Comment by mo-marqh** [comment]
`Product discipline 0 - Meteorological products, parameter category 0: temperature	10		Latent heat net flux`

from WMO 4.2 is worth consideration but the nuance between `latent heat net flux` and `surface_upward_latent_heat_flux` may justify a local code and a paragraph exploring the nuance of this parameter as generated

**Comment by feggleton** [comment]
confirmed by Bruce that local code is no longer needed as WMO code 0-0-10 is correct. See GRIB mapping repo for details.
